services:
  mysql:
    image: mysql:8.4
    container_name: bench_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: benchmark_test
    ports:
      - "3306:3306"
    command: >
      --local-infile=1
      --innodb_buffer_pool_size=1G
      --innodb_redo_log_capacity=512M
    deploy:
      resources:
        limits:
          memory: 8g

  mariadb:
    image: mariadb:11
    container_name: bench_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: benchmark_test
    ports:
      - "3307:3306"
    command: >
      --local-infile=1
      --innodb_buffer_pool_size=1G
      --innodb_log_file_size=256M
    deploy:
      resources:
        limits:
          memory: 8g

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bench_sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Benchmark@123
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          memory: 8g

  postgresql:
    image: postgres:18-alpine
    container_name: bench_postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: benchmark_test
    ports:
      - "5432:5432"
    command: 
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"
    deploy:
      resources:
        limits:
          memory: 8g

  mongodb:
    image: mongo:8.0
    container_name: bench_mongodb
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 8g

  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: bench_oracle
    environment:
      ORACLE_PASSWORD: 123456
      APP_USER: benchmark
      APP_USER_PASSWORD: 123456
    ports:
      - "1521:1521"
    shm_size: 2g
    deploy:
      resources:
        limits:
          memory: 8g